config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
    
  get '/home', to: 'pages#home'
  
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post '/recipes', to: 'recipes#create'
  #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id/', to: 'recipes#update'
  #get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  #delete '/recipes/:id', to: 'recipes#destroy'
  
  resources :recipes
  
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                                    uniqueness: { case_sensitive: false },
                                    format: { with: VALID_EMAIL_REGEX }
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "shoud be less than 5MB")
      end  
    end
end

app/controllers/.rb
class PagesController < ApplicationController
  
    def home
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
    def home
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end
  
  def show
    @recipe = Recipe.find(params[:id])
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.find(1)

    if @recipe.save
      flash[:success] = "Your recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated successfully"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
    
  end
  
  private
    
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; MyRecipes 2015</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "my receipes", root_path, class: "btn btn-lg btn-success", id: "logo" %>
    <div class="nav_item">
      <%= link_to "link 1", "", class: "btn btn-default btn-warning" %>
    </div>
    
    <div class="nav_item">
      <%= link_to "link 2", "", class: "btn btn-default btn-warning" %>
    </div>
    
    <div class="nav_item">
      <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>
  
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>

    <%= render 'layouts/footer' %>
  
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to My Receipes App</h1>
    <h2>
        This is the home page for the professional Ruby on Rails developer course on Udemy
    </h2>
    <%= link_to "Sign up now", "", class: "btn btn-lg btn-success" %>
</div>
<div class="row">
    <div class="col-lg-4">
        <h3 class="midrow">
            View Receipes as Guest user
        </h3>
        <h2 class="left">Browse and view receipes as a guest and Sign up later</h2>
        <p><%= link_to "Browse Receipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
    </div>
        <div class="col-lg-4">
        <h3 class="midrow">
            View Receipes as Guest user
        </h3>
        <h2 class="left">Browse and view receipes as a guest and Sign up later</h2>
        <p><%= link_to "Browse Receipe Listings", "", class: "btn btn-warning btn-small" %></p>
    </div>
        <div class="col-lg-4">
        <h3 class="midrow">
            View Receipes as Guest user
        </h3>
        <h2 class="left">Browse and view receipes as a guest and Sign up later</h2>
        <p><%= link_to "Browse Receipe Listings", "", class: "btn btn-warning btn-small" %></p>
    </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      
      <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function() { 
    size_in_megabytes = this.files[0].size/1024/1024;
    if ( size_in_megabytes > 5) {
      alert('Maximum file size is 5MB Please choose a smaller file');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All recipes" %>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for recipe.chef, size: 100 %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>
    
    <div class="col-lg-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <span class="quiet"><small><%= time_ago_in_words(recipe.created_at) %></small></span></span>
      </p>
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
    
  </div>
<% end %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
  <div class="col-md-r pull-right center">
    <%= gravatar_for @recipe.chef, size: 200 %>
    <p>
      <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
    </p>
  </div>
  <div class="col-md-8">
    <%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
    </div>
    <div class="well">
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
    </div>
  </div>
</div>

<h5><%= link_to "Return to Recipes Listing", recipes_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr/>
</p>